### ISSUE TITLE
[1.316] Subtractive brushes do not subtract from collision mesh

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#68] opened 2016-11-04 20:45 UTC
![Example](http://i.imgur.com/irfFchK.jpg)

Simple bug, subtractive geometry does not subtract from the final collision mesh. My player cannot fall through the holes in the floor in the above image.

Edit:

![Example2](http://i.imgur.com/tGY7SfC.jpg)

It also appears that subtractive brushes also have a collision mesh of their own. In the example image I cannot walk through the subtractive brush.

Also, the subtractive brush changes the material of the floor. Probably shouldn't do that.

Edit edit...: I realise this is all because these brushes are part of the same CSG Model and automatically generate colliders for every brush inside them. Could this be fixed without requiring me to seperate these brushes into different models?

**Comment by LogicalError** [comment] 2016-11-05 08:05
Hi!
I'm sorry but what you're saying about subtractive brushes is literally impossible. At the moment the meshes for rendering are the same meshes as those used for physics. so if it's not being rendered it doesn't exist for physics either, so something else must be going on. I suspect that in your model, in the unity inspector, set to convex might be turned on, or your model might not be set to static (Unity handles static colliders differently than non-static colliders)
could you sent me your scene by email so I can take a closer look?

Subtractive brushes will replace any surface it touches by it's own surface, that's actually by design.. is this a big problem for you?

**Comment by sonygod** [comment] 2016-11-05 08:29
+1 ,I hope subtractive can really cut / seperate the brush. let it have their own material, physics collision

**Comment by Drexen** [comment] 2016-11-05 13:52
![Example](http://i.imgur.com/rKcXjO0.jpg)

In the example the blue highlighted arch is part of the same model as all of my world geometry of the level and the subtractive center part is still solid. The red arch however is part of a new CSGModel seperate from the rest of the level geometry and the center is passable. Both CSGModels are static and "Set Collider To Convex" is unchecked.

**Comment by LogicalError** [comment] 2016-11-06 12:25
Could you send me a scene with that part so I can take a look at it? thanks

**Comment by Drexen** [comment] 2016-11-06 14:48
I've sent the scene to your email.

**Comment by LogicalError** [comment] 2016-11-14 19:07
Ok, I looked at your repro case and it seems that a mesh that's only used for rendering in the editor is somehow included in the player build (which shouldn't happen)
I'll work on a fix asap

**Comment by LogicalError** [comment] 2016-11-14 23:27
This issue is fixed in version 1.316 which can be found on the update site 
( http://prenominal.nl/updates/index.php )
I'll close this ticket when this version is on the asset store

**Comment by LogicalError** [comment] 2016-11-29 08:27
This version is now available on the asset store, so closing ticket

**Closed by LogicalError** 2016-11-29 08:27 UTC
Labels: Fix available
