### ISSUE TITLE
Raycasting sometimes selects wrong surface

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#285] opened 2019-01-20 07:34 UTC
https://cdn.discordapp.com/attachments/531079135737544705/534044194440871997/WallSelect.gif

**Comment by LogicalError** [comment] 2019-03-06 07:47
turns out selection is correct, but the CSG algorithm is sometimes not removing the right surfaces when they're really close to each other

**Comment by Kerfuffles** [comment] 2022-04-14 09:21
I haven't noticed this issue with more recent versions of RCSG. Can this be closed?

**Comment by alexjhetherington** [comment] 2022-04-22 16:01
Unable to reproduce in 2019 LTS, 2021 LTS +1 for closing

**Comment by Appleguysnake** [comment] 2022-11-10 17:58
Haven't had this problem with the latest versions and in Unity 2021, +1 close

**Closed** 2023-01-10 17:09 UTC
Labels: Bug, Cannot reproduce
