### ISSUE TITLE
[1.332] Dragging model from one scene to another does not rebuild the mesh(es) in inactive scenes

### ISSUE THREAD

**Issue by kdgalla** [LogicalError/realtime-CSG-for-unity#73] opened 2016-11-07 03:34 UTC
I have another problem now.

My plan is to have a "main scene" which has the global game objects like main character and event handler and things like that. All of the levels would be in second scenes that would be loaded additively as needed. 

The problem is that when I generate a new model, it adds it to the first scene loaded. When I drag the model from the main scene to the second scene and go into playmode, it starts to get buggy. The model is no longer rendered in the editor or in play mode. When the model or brush is selected in the editor, only the bounding box is visible. There are warning messages in the console, like the following:

Cross scene references are not supported: '[model-mesh] Model' in scene MainScene has an invalid reference to 'Model' in scene Basement1. This reference will not be saved in the scene.

**Comment by LogicalError** [comment] 2016-11-08 20:23
So .. does your problem have anything to do with Realtime-CSG?

**Comment by kdgalla** [comment] 2016-11-08 23:07
Sorry if I worded it in a confusing way. Basically I am experiencing a bug where, when I have two scenes loaded in the editor, sometimes brushes stop rendering. At first I thought it only happened When I moved a model from one scene to another scene, but later I discovered the problem eventually occurred again, even if I kept all of my Realtime CSG objects in the default scene. I'll see if I can make a repro project.

**Comment by LogicalError** [comment] 2016-11-10 22:40
A repro would be awesome :)
It's the quickest way for me to fix the issues you're having for you ..

**Comment by kdgalla** [comment] 2016-11-12 04:29
I have created a repro project for this issue and emailed it to you.

**Comment by LogicalError** [comment] 2016-11-14 18:53
Ok, I can confirm that the issue is that dragging a model from one scene to another does not rebuild the mesh(es) in inactive scenes.

**Comment by LogicalError** [comment] 2016-12-05 16:04
This is fixed in version 1.332!
As usual this is available on the update site https://prenominal.nl/updates/
I'll close this ticket once this version is available from the asset store!

**Closed** 2016-12-08 19:35 UTC
Labels: Fix available
