### ISSUE TITLE
[1.323] Change the way height handle manipulation works

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#126] opened 2016-11-22 01:02 UTC
What I did:
- Made a new scene.
- Drew a box brush base.
- Extended its height.
- Rotated the camera about 90 degrees on the y axis.
- Drew another box brush on top of the first one.
- Dragged its height handle. ([Screen recording](http://imgur.com/S95Wxf3))

What happened:
- The second box's height handle behaved erratically and unpredictably.

Other info:
- This issue happens both moving from facing X to Z and vice versa.
- Moving the camera after making a new scene affected its reproducibility (although caused it to occur on the first brush instead of the second, at times)
- It generally seems to be related to be related to which perspective you created the previous brush from, affected across scenes.

Platform: OSX
Unity version: 5.4.0f3 personal
RCSG version: 1.319

**Comment by LogicalError** [comment] 2016-11-22 15:40
This is not caused by the rotation, it's more that there's an invisible, infinite plane over which you move the mouse and this plane is orientated with the direction of movement .. the advantage is that your mouse cursor will always match the position of the brush, the downside is that you can essentially move your brush into infinity. 
It might make sense to use a different approach though, being able to properly move the brush is more important than the position of the mouse

**Comment by LogicalError** [comment] 2016-11-22 20:27
This is partially implemented in version 1.321 (only for shape generation right now)
This version is available on the update site https://prenominal.nl/updates/

**Comment by AlexanderOcias** [comment] 2016-11-22 21:10
Please take another look at my screen recordings - I believe I understand the way the planes work (and I really liked their perfect-mouse-position behaviour, it would be a big shame to lose it!), and I still believe this may in fact a rare bug in the axis selection for that plane, not just a side-effect of your approach.

Observe that in the first brush I draw, the infinite plane is correctly on the XY axis. Then when I rotate the view and make the second brush, the infinite plane is still on the XY axis, while the expectation is that the infinite plane would now be aligned to the YZ axis.

[Here is another screen recording with the axis behaviour labelled](url).

Finally, [here is a screen recording of a simple worst case example of this bug](http://imgur.com/vaL8Mve).

**Comment by LogicalError** [comment] 2016-11-23 16:41
Ok, this is fixed in version 1.323 (should work the way you'd like now)
This version is available on the update site https://prenominal.nl/updates/
I'll close this ticket when it's available from the asset store

Thanks for the help!

**Closed** 2016-12-08 19:34 UTC
Labels: Request implemented
