### ISSUE TITLE
Hard crashes when you click on any UV related buttons

### ISSUE THREAD

**Issue by olegmrzv** [LogicalError/realtime-CSG-for-unity#325] opened 2021-08-01 22:56 UTC
OS: MacOS 10.15.7
Unity: 2020.3.* (tested on several minor builds)
RCSG: 1.562 (Asset Store) and 1.569 (GitHub)

When you click on any of these buttons in the surfaces window, a hard crash occurs.
![image](https://user-images.githubusercontent.com/5537684/127787612-3e8d02cc-e5d3-43cc-8626-4c343d2dcf2a.png)

Looking at the dump it refers to the С++ function GetSurfaceMinMaxTexCoords.
![image](https://user-images.githubusercontent.com/5537684/127787610-608157c4-b4da-43d1-bf9f-6b839aacbf3c.png)

**Comment by LogicalError** [comment] 2022-03-07 09:22
Cannot reproduce, can you supply us with the scene you used when it crashed?

**Comment by Kerfuffles** [comment] 2022-04-14 08:44
Do you still have this issue @olegmrzv?

**Comment by Kerfuffles** [comment] 2022-06-10 00:48
Closing this issue as I am unable to reproduce, and OP has not responded in several months.

**Closed by Kerfuffles** 2022-06-10 00:48 UTC
Labels: Bug
