### ISSUE TITLE
Using Shift+Click or Ctrl+Click to add a CSG brush to the selection will also add whatever is behind it

### ISSUE THREAD

**Issue by lazlo-bonin** [LogicalError/realtime-CSG-for-unity#287] opened 2019-01-24 21:54 UTC
As the title says. If I have one brush selected and want to select another one, Shift/Ctrl+LMBing on the second brush will add it to the selection, but it will also add whatever non-brush object is behind it.

Makes it pretty much impossible to add an item to the selection right now, which is my main pain point.

**Comment by LogicalError** [comment] 2019-03-06 07:43
Thanks, I'll take a look

**Comment by Kerfuffles** [comment] 2022-06-10 00:54
I am unable to reproduce this issue, and it has been present for a long time. I think I remember a post or something somewhere mentioning this was fixed? I will be closing this issue for now, unless someone else *can* reproduce this issue.

**Closed by Kerfuffles** 2022-06-10 00:54 UTC
Labels: Bug
