### ISSUE TITLE
[Request] Snap meshes to grid while dragging

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#130] opened 2016-11-22 11:40 UTC
What I did:
- Dragged a prefab from my project onto my CSG model.
- [(Screen recording)](http://imgur.com/0nlhNCq).

What happened:
- No snapping.

What I expected:
- The prefab's pivot to snap to the surface of the CSG model, as it does with other meshes.

Other info:
Platform: OSX 10.11.6
Unity version: 5.4.0f3 personal
RCSG version: 1.320

**Comment by LogicalError** [comment] 2016-11-22 15:37
This is a mesh that you're dragging, not a brush?

**Comment by AlexanderOcias** [comment] 2016-11-22 20:27
Yep.

**Comment by LogicalError** [comment] 2016-11-22 20:37
Ah ok, that's not a bug then. That was never part of realtime-CSG.
There is another feature request for this however: #100

**Comment by AlexanderOcias** [comment] 2016-11-22 21:18
Wait a sec, I'm not trying to snap the meshes to the grid, I'm trying to snap the pivot to the *surface* of the CSG model during the initial drag-in, the same way it does with the mesh on the right in my screen recording - just default unity behaviour, nothing to do with any grid.

**Comment by LogicalError** [comment] 2016-12-05 10:26
Ok, I'll look into it, thanks for clarifying this

**Comment by LogicalError** [comment] 2017-01-26 15:36
Related to #62

**Comment by LogicalError** [comment] 2017-05-07 15:54
This is implemented in version 1.406, which can be found on the support website ( https://prenominal.nl/updates/ )
I will close this ticket once this version is available from the asset store

**Closed** 2018-03-08 09:12 UTC
Labels: Request implemented
