### ISSUE TITLE
[Fix Available 1.309] Scaling group of objects with different rotations

### ISSUE THREAD

**Issue by MarisaLovesUsAll** [LogicalError/realtime-CSG-for-unity#28] opened 2016-10-16 18:31 UTC
Let us have some objects:
![untitled](https://cloud.githubusercontent.com/assets/5061652/19419718/18e747d8-93e6-11e6-8958-540d11a9044a.png)

We want to scale the whole railing, so we select scale mode and make an attempt to scale it:
![bug](https://cloud.githubusercontent.com/assets/5061652/19419761/35946db0-93e7-11e6-9ec7-cc5e86b9f7af.gif)
Objects sizes are scaled somewhat properly, but the distance between objects is completely messed up.
Also the origin coordinate is not ok too.

Glass parts are the boxes, rotated & clipped.
Tubes are the boxes without rotation (just clipped).

Not sure if bug or feature. :)

**Comment by LogicalError** [comment] 2016-10-17 08:52
Ah, no this is most definitely a bug.
Thanks for reporting this, I'll look into it

**Comment by LogicalError** [comment] 2016-10-17 14:18
Could you sent me those couple of brushes that show this behavior? (my email addres can be found at https://logicalerror.github.io/ in the top right corner)
It'll help me with testing .. thanks

**Comment by LogicalError** [comment] 2016-10-17 18:49
I have not been able to reproduce this .. so if you could send me a scene with those brushes through email, I'd appreciate it. thanks

**Comment by MarisaLovesUsAll** [comment] 2016-10-17 20:56
Sent a prefab with railing, check it out.

**Comment by MarisaLovesUsAll** [comment] 2016-10-18 20:53
Holy crap, it was my fault after all.

This little button was set to «Local».

![untitled](https://cloud.githubusercontent.com/assets/5061652/19495595/a9cc5070-958c-11e6-9d62-1eddf489abe6.png)

When it is set to Global, all works as expected.

However, I still can't see any logic behind «Local» mode, no matter what mode («Pivot» or «Center») is checked in the second button.

**Comment by LogicalError** [comment] 2016-10-25 17:51
I'll take a look, it doesn't look like how I'd expect "local" to work, but it does explain why I couldn't reproduce it ;p

**Comment by LogicalError** [comment] 2016-10-26 20:45
This issue is fixed in version 1.309 which is available on the update site 
( http://prenominal.nl/updates/index.php )
I will close this ticket when it's available on the asset store

**Comment by LogicalError** [comment] 2016-11-10 08:19
Fix is in the version that's on the asset store now, so closing ticket

**Closed by LogicalError** 2016-11-10 08:19 UTC
Labels: Fix available
