### ISSUE TITLE
X and Z axes transposed when creating a Box?

### ISSUE THREAD

**Issue by DavidAntliff** [LogicalError/realtime-CSG-for-unity#323] opened 2021-05-07 07:03 UTC
I'm very new to realtime-CSG so apologies if this has already been reported, or I've missed something.

When I go to create a Box using the Generate menu, and manually type values into the Height, Length and Width fields, the axis that the rectangle changes does not match the label on the field.

Specifically, the "Length (X)" field seems to set the dimension in the local Z axis.
The "Width (Z)" field seems to set the dimension in the local X axis.

For example, if I create a box with Height 0.1, Length 1.0 and Width 0.5, then it ends up creating a "brush" with the local Y axis height of 0.1, but local X axis of 0.5, and local Z axis of 1.0.

It's as if the X and Z axes are transposed.

I'm using v1.562.

**Comment by Kerfuffles** [comment] 2022-04-14 23:36
This issue is caused by `Scripts/View/GUI/EditModeGUI/EditModes/Generators/Generator.Box.GUI`, where `generator.Length` and `generator.Width` seemed to have gotten mixed up with each other and used in the wrong double field.

This will be fixed when #349 gets merged.

**Comment by Janooba** [comment] 2022-06-13 22:41
Confirmed fixed in #349 using 2019.4.31f1

**Closed** 2022-11-06 22:47 UTC
Labels: Bug, Fix available
