### ISSUE TITLE
[1.326] render interior?

### ISSUE THREAD

**Issue by kdgalla** [LogicalError/realtime-CSG-for-unity#72] opened 2016-11-06 22:46 UTC
Hello I installed version 1.303 in a new project (Unity 5.4.1 64bit). I'm trying to create a plain, blank, rectangular room, but it's not working like I would expect. 

I create a model with a big box and subtract a small box from inside in order to create an interior room. I'm not able to assign a surface to the box inside. In the editor it shows a blue grid with "invisible" written on it.  When I run the scene with the camera inside, nothing renders, only the skybox.
This is different than I expect, because I would expect it to create an empty room with the same material that is assigned to the larger box. At least, I would have thought that I should be able to assign

Similarly, I create a box and click the "inverted world" check box. I was expecting that it would render the inside of a box with the default surface, but actually it turns into the editor "invisible" grid pattern and I'm not able to assign any surface material to it.

**Comment by LogicalError** [comment] 2016-11-06 22:49
Hi, have you tried version 1.313?

**Comment by kdgalla** [comment] 2016-11-06 23:45
Thanks. I downloaded version 1.313 and started over, but I get the same results.

**Comment by kdgalla** [comment] 2016-11-07 01:00
Additional information: If the small interior box overlaps the large exterior box, it creates a room with three walls, a floor and a ceiling, and the materials are applied exactly as I would expect.

**Comment by kdgalla** [comment] 2016-11-08 01:18
I think that this problem may be related to the multi-scene editing problem that I posted about later (#73). When I unload the "main scene". Everything seems to work like it should. At that point I am only editing one scene. 

I still would like to have this work with multiple scenes open.

**Comment by LogicalError** [comment] 2016-11-08 20:28
Are both brushes in different scenes, or the same one?

**Comment by kdgalla** [comment] 2016-11-08 22:55
All in one scene.

**Comment by LogicalError** [comment] 2016-11-10 22:39
I looked at this and I can't reproduce this .. the only way I get the "invisible grid", which I assume you mean is the texture that's shown when a surface is invisible (and in the bottom bar showing invisible surfaces is turned on), is if I put an additive brush inside an additive brush ..
If you put an additive brush within an additive brush, then the second brush will just disappear.
If this is what's happening, then you can simply make the second brush subtractive and it should do what you mean.
If this is something else then I'll need a repro ...

**Comment by LogicalError** [comment] 2016-11-14 19:11
When I looked at the repro scene that you sent me for another bug the small box in a big box looked fine on my end .. perhaps I didn't understand what you meant?

**Comment by kdgalla** [comment] 2016-11-16 03:08
I'm have not been able to repro this problem.

**Comment by LogicalError** [comment] 2016-11-16 13:14
Ok .. well let me know if you run into this again

**Comment by LogicalError** [comment] 2016-11-23 16:36
This might be related to #122  ...

**Comment by LogicalError** [comment] 2016-11-27 19:16
I'm going to assume this is the same as #122, which is now fixed in version 1.326, which can be downloaded from https://prenominal.nl/updates/
I'll close this ticket once this version is available on the asset store

**Closed** 2016-12-05 16:05 UTC
Labels: Fix available
