### ISSUE TITLE
Make a brush wrong position

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#248] opened 2018-04-02 13:46 UTC
RealtimeCSG makes a brush an unintended position. This issue happens when you make a brush in the subtracted hollow.

![realtimecsg](https://user-images.githubusercontent.com/7605365/38198362-7977e71c-36c7-11e8-9280-02c9848a0bbc.gif)

**Comment by LogicalError** [comment] 2018-04-03 13:03
Thanks for letting me know. The problem is because the ray cast from the mouse to the surface should ignore a removed polygon, but doesn't. I'll fix this in 1.524

**Comment by LogicalError** [comment] 2018-04-05 21:32
This has been fixed in 1.524, which I just uploaded to RealtimeCSG.com .. I'll close this ticket once this version is available from the asset store!

**Comment by Hisashimaru** [comment] 2018-04-06 01:07
Thanks for fixing it. Brushes are still made in the wrong place.

**Comment by LogicalError** [comment] 2018-04-06 09:58
Sorry about that, try version 1.525. There was a typo which made this not work in the Y direction ..

**Comment by Hisashimaru** [comment] 2018-04-07 01:45
It works well! Thanks for quick fix.

**Closed** 2018-09-11 11:59 UTC
Labels: Fix available
