### ISSUE TITLE
Rotation handles not always appearing in 2020.2.1f1 / URP

### ISSUE THREAD

**Issue by cr4yz** [LogicalError/realtime-CSG-for-unity#319] opened 2021-01-17 20:01 UTC
In Unity 2020.2.1f1 + URP 10.2.2 the RealtimeCSG rotate handle does not always appear when hovering a brushes bounds.  It renders when Event.current.type is EventType.Repaint, but the Repaint event does not call on mouse move.

I've hacked in a quick fix here: 
https://github.com/LogicalError/realtime-CSG-for-unity/blob/03adff579cc82167b2dd5d226ec89cd6745249fe/RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModes/EditMode.Place.cs#L1358

`if(Event.current.type == EventType.MouseMove)
{
	sceneView.Repaint();
}`

**Comment by cr4yz** [comment] 2021-01-22 17:34
Found a toggle in editor causing this: https://i.imgur.com/8AcKisH.png

I just put this in SceneViewEventHandler to force it on: sceneView.sceneViewState.alwaysRefresh = true;

**Comment by Kerfuffles** [comment] 2022-04-26 02:12
Fixed with #349

**Comment by Janooba** [comment] 2022-06-13 22:56
Confirmed fixed in #349 using Built-In@2019.4.31f1 and URP@2020.3.35f1

**Closed** 2022-11-06 22:47 UTC
Labels: Bug, Fix available

**Comment by pdinklag** [comment] 2023-12-13 05:26
Unity 2022.3.13 in URP here. I can only get the rotation handles to show up *very* sporadically (and they disappear again after moving the mouse minimally) and almost never for the intended axis to the point where it's basically impossible to rotate anything. It doesn't seem related to URP, but since this issue exists, maybe it does?
