### ISSUE TITLE
[1.323] Invisible and discarded surfaces block GI

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#125] opened 2016-11-21 11:18 UTC
- Invisible and discarded surfaces block both realtime and baked GI ([screenshot](http://imgur.com/eJIyzAR))
- Manually disabling visibility of those surfaces before building lighting avoids this bug

**Comment by LogicalError** [comment] 2016-11-21 14:35
I'll look into it, I think I already know what's causing this ..

**Comment by LogicalError** [comment] 2016-11-21 15:22
hmm .. I can't seem to reproduce this?
Are you using Unity version 5.4.0f3? Are all brushes in the same model?

**Comment by LogicalError** [comment] 2016-11-21 15:23
How did you make the surfaces "discarded"? Did you assign the "discarded" material manually?

**Comment by AlexanderOcias** [comment] 2016-11-21 21:31
Yep, 5.4.0f3, all brushes the same model. I selected all the faces manually and discarded them via the surface tools. The invisible brush is just a subtractive one.

**Comment by AlexanderOcias** [comment] 2016-11-21 23:07
I've emailed you an example scene, hopefully it makes it easier to reproduce.

**Comment by LogicalError** [comment] 2016-11-23 15:46
Hmmm ... that seems to be an unity bug (unless I'm misunderstanding something) .. the meshes are set to not cast shadows. I'll workaround this

**Comment by LogicalError** [comment] 2016-11-23 16:40
This is fixed in version 1.323 
This version is available on the update site https://prenominal.nl/updates/
I'll close this ticket when it's available from the asset store

**Closed** 2016-12-08 19:34 UTC
Labels: Fix available
