### ISSUE TITLE
Performance is poor when editing

### ISSUE THREAD

**Issue by jmickle66666666** [LogicalError/realtime-CSG-for-unity#225] opened 2017-12-09 14:57 UTC
I get very poor performance on my machine when using Realtime CSG. I have to shrink my scene view significantly to use at a decent framerate. When doing this I can just about use it, but it is still not smooth. Particularly the Generate, Mesh and Clip modes are very slow, making any kind of precision very difficult.

These issue slow down my process significantly, and generally make using the tool not much fun.

My machine specs are as follows:
MacBook Pro (Retina, 15-inch, Mid 2015)
Processor: 2.2 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Graphics: Intel Iris Pro 1536 MB

**Comment by LogicalError** [comment] 2017-12-11 07:41
What does your scene look like? Does it have a lot of brushes and/or models? Also what version of Realtime-CSG are you using?

**Comment by jmickle66666666** [comment] 2017-12-11 07:51
The scene can be empty and have poor performance. Using the clip tool especially, moving the mouse over a few brushes can get really slow. I'm using v 1.504

**Comment by LogicalError** [comment] 2017-12-11 07:53
Can you try version 1.507? 
You can find it here https://realtimecsg.com/updates/

**Comment by jmickle66666666** [comment] 2017-12-11 08:10
This version does run a little better when using a small window like I have been doing so far. I recorded a gif which roughly shows how it performs for me.

![realtime](https://user-images.githubusercontent.com/7083717/33821036-950e8346-de52-11e7-94c5-5aafe571a718.gif)

As you can see while it is usable and I am managing to build scenes, the delay between some actions or movements (in particular delays like the last movement extruding the brush) can make precision actions very difficult and slow down my workflow a lot.

**Comment by LogicalError** [comment] 2017-12-11 16:15
Hi, I have some performance improvements to the line rendering & rewrote some unity code from scratch that dealt with how far a mouse cursor is away from a point or line .. apparently the stock Unity methods that deal with that are ridiculously slow. This should help, I'll try to release it soon

**Comment by jmickle66666666** [comment] 2017-12-11 20:55
Excellent! I look forward to trying it out 

Re: my machine, it's definitely far from perfect for this kind of thing but this isn't a thing it should be struggling with. Unity itself runs well for me, I have to push it pretty hard with complex scenes to get it to slow down too much. I occasionally make videos of my work too and still have a good enough performance while it's recording.

**Comment by LogicalError** [comment] 2017-12-12 08:18
I forgot to ask, what version of Unity are you on? I'm wondering if that's a factor in this

**Comment by LogicalError** [comment] 2017-12-12 20:05
can you try out version 1.509? it should help with the issues you're currently having 
https://realtimecsg.com/updates/

**Comment by otdavies** [comment] 2017-12-24 06:39
When working on the mesh is it marked as static? If it is static it will slow down the editor to a crawl. You need to mark it as not static while working on it.

**Comment by LogicalError** [comment] 2017-12-24 11:15
Could it be that in the lighting window "Auto Generate" is turned on? Then unity will start recalculating the lighting for the scene every time a mesh is changed (which happens every time you edit something in realtime CSG on a model that is marked 'static' for light-mapping). Turning off auto and only recalculating the lighting when you want to should help in that scenario

**Comment by LogicalError** [comment] 2017-12-27 08:43
Another culprit could be that on the model Auto Rebuild Uvs is on, which rebuilds the lightmap uvs after you make a change to your model. This calls into a unity method to calculate the lightmap uvs, which can be really slow.

**Comment by LogicalError** [comment] 2018-01-03 15:46
can you try out version 1.510? it has some optimizations that have to do with ray-casting into the scene, which can be slow when moving the mouse in the scene, maybe that's the cause of your performance issues?
you can find the update here: https://realtimecsg.com/updates/

Feedback is appreciated!

**Comment by jmickle66666666** [comment] 2018-01-03 18:32
Hello sorry I've not tried this out yet, I've been very busy recently. Will try and make some time for this soon!

**Comment by LogicalError** [comment] 2018-03-08 09:00
FYI; latest version (1.517)  has loads of performance improvements

**Closed** 2018-09-11 13:51 UTC
Labels: Investigating
