### ISSUE TITLE
1.530 Doesn't load properly on OSX

### ISSUE THREAD

**Issue by mkapolka** [LogicalError/realtime-CSG-for-unity#260] opened 2018-07-31 02:56 UTC
I tried downloading the latest 2018.1 version of 1.530 on OSX and it gave me a DllNotFoundException. I downloaded 1.529 and that worked fine. It looks like there are some more files in the `RealtimeCSG[1.529].bundle` directory. Maybe some files got left out of 1.530? 

Here's a relevant-looking stack trace from the editor logs:
```
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/RealtimeCSG[1.530]
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].bundle
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/RealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/RealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./RealtimeCSG[1.530]
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].bundle
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./RealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./RealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/RealtimeCSG[1.530]
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530]
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].bundle
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530]
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].bundle
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530]
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/RealtimeCSG[1.530]
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].bundle
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/RealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/RealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./RealtimeCSG[1.530]
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].bundle
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./RealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./RealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/RealtimeCSG[1.530]
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530]
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530].bundle
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530]
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].dylib
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].so
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/./libRealtimeCSG[1.530].bundle
Fallback handler could not load library /Applications/Unity/Hub/Editor/2018.2.1f1/Unity.app/Contents/Frameworks/Mono/lib/libRealtimeCSG[1.530]
DllNotFoundException: RealtimeCSG[1.530]
  at (wrapper managed-to-native) RealtimeCSG.Foundation.CSGManager:HasBeenCompiledInDebugMode ()
  at RealtimeCSG.Foundation.CSGManager.get_VersionName () [0x0000b] in /Users/mkapolka/art/dungeon/Assets/Plugins/RealtimeCSG/API/Foundation/Editor/CSGManager.cs:66 
  at RealtimeCSG.EditModeSelectionGUI..cctor () [0x00102] in /Users/mkapolka/art/dungeon/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeSelection.GUIContents.cs:40 
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for RealtimeCSG.EditModeSelectionGUI
  at EditModeToolWindowEditor.OnInspectorGUI () [0x0001c] in /Users/mkapolka/art/dungeon/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeToolWindow.Editor.cs:16 
  at UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor[] editors, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) [0x0044b] in /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1374 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEditor.InspectorWindow:DrawEditor(Editor[], Int32, Boolean, Boolean&, Rect&) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1381)
UnityEditor.InspectorWindow:DrawEditors(Editor[]) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1141)
UnityEditor.InspectorWindow:OnGUI() (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:481)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
System.Reflection.MethodBase:Invoke(Object, Object[]) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView:Invoke(String, Object) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView:Invoke(String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView:InvokeOnGUI(Rect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:255)
UnityEditor.DockArea:OldOnGUI() (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:390)
UnityEngine.Experimental.UIElements.IMGUIContainer:DoOnGUI(Event, Boolean) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:215)
UnityEngine.Experimental.UIElements.IMGUIContainer:HandleIMGUIEvent(Event) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:377)
UnityEngine.Experimental.UIElements.IMGUIContainer:DoRepaint(IStylePainter) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:89)
UnityEngine.Experimental.UIElements.Panel:PaintSubTree(Event, VisualElement, Matrix4x4, ClippingOptions, Rect) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/Panel.cs:732)
UnityEngine.Experimental.UIElements.Panel:PaintSubTreeChildren(Event, VisualElement, Matrix4x4, ClippingOptions, Rect) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/Panel.cs:748)
UnityEngine.Experimental.UIElements.Panel:PaintSubTree(Event, VisualElement, Matrix4x4, ClippingOptions, Rect) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/Panel.cs:736)
UnityEngine.Experimental.UIElements.Panel:Repaint(Event) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/Panel.cs:778)
UnityEngine.Experimental.UIElements.UIElementsUtility:DoDispatch(BaseVisualElementPanel) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:227)
UnityEngine.Experimental.UIElements.UIElementsUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:74)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:171)
 
(Filename: Assets/Plugins/RealtimeCSG/API/Foundation/Editor/CSGManager.cs Line: 66)
```

**Comment by LogicalError** [comment] 2018-08-13 11:48
Hi, can you try version 1.531?
If that doesn't work, what version of OSX are you on?

**Comment by mkapolka** [comment] 2018-08-17 16:08
Hm, I can't seem to download that because my order number is no longer recognized on the website and the asset store doesn't have 1.531

**Comment by LogicalError** [comment] 2018-08-17 17:39
Can you send me your order number? Then I can check if the problem is on the website or at Unity
I'll try to update the asset store version soon then

**Comment by mkapolka** [comment] 2018-08-18 15:06
Emailed.

**Comment by LogicalError** [comment] 2018-08-21 18:34
Version 1.532 should fix this issue, let me know if you're still having issues
I'll close this ticket when this version arrives on the asset store

**Comment by LogicalError** [comment] 2018-09-17 07:07
This is available from the asset store, closing this ticket

**Closed** 2018-09-17 07:07 UTC
Labels: Fix available
