### ISSUE TITLE
[Fix Available 1.306] Multi select surfaces

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#25] opened 2016-10-16 08:19 UTC
Realtime CSG supports select multi surfaces on Surface Mode? I try to select surfaces with Shift+Click, but I couldn't.

Realtime CSG 1.305
Unity 5.4.2f1

**Comment by Hisashimaru** [comment] 2016-10-16 11:33
I found the solution!
You can select surfaces with Shift/Ctrl + Click and Small Drag

Select surfaces with click and small drag each surface by design?

**Comment by LogicalError** [comment] 2016-10-17 09:03
No the small drag is not by design .. I'll take a look, thanks for reporting this

**Comment by LogicalError** [comment] 2016-10-17 18:24
Fixed in version 1.306, which is available on the update site ( https://logicalerror.github.io/ )
Once this version is on the asset store I'll close this bug.

**Comment by LogicalError** [comment] 2016-11-10 08:17
Fix is in the version that's on the asset store now, so closing ticket

**Closed** 2016-11-10 08:19 UTC
Labels: Fix available
