### ISSUE TITLE
[1.328] Grid Lines can't see on Models

### ISSUE THREAD

**Issue by Cyber2017** [LogicalError/realtime-CSG-for-unity#133] opened 2016-11-24 09:20 UTC
Hello... K, the Grid Lines are only Visible around the Models, not inside the Models... Snapping though works great but the other thing makes Modeling kinda difficult.. Using the New Unity 5.5.0f1 & Unity 5.5b11
This issue was with both Versions of unity.. I'm now using the newest as of yesterday..
Thanks :)

**Comment by LogicalError** [comment] 2016-11-24 10:27
Can you add a screenshot so I can see what you mean exactly?
Thanks

**Comment by Cyber2017** [comment] 2016-11-25 11:48
Absolutely, here's a Top View ...

**Comment by Cyber2017** [comment] 2016-11-25 11:51
Oh, and doesn't matter if I magnify view, or change any settings. This happened also with Unity 5.5b11; I'm now using 5.5.0f1 (Latest Version)

**Comment by LogicalError** [comment] 2016-11-27 19:25
Ok .. I can't reproduce this.

The grid lines should be visible if you're in orthographic mode (non "perspective" mode) ..
It's sort of related to #83, I think makes sense to show 'hidden' grid lines in a different color so that you can still see it in perspective mode as well

**Comment by Cyber2017** [comment] 2016-11-28 01:02
Not sure if it was me doing something wrong.. I'll test tonight to see if all is good with your New Version 1.327 ... Oh, yes I'll make sure "orthographic mode" is picked :)

Thanks, keep up the Awesome! Updates..

**Comment by LogicalError** [comment] 2016-11-28 16:07
This is improved in 1.328! 
You can download it at the update site https://prenominal.nl/updates/
Once this version is available from the asset store, I'll close this ticket

**Closed** 2016-12-08 19:34 UTC
Labels: Request implemented
