### ISSUE TITLE
Cannot select brushes anymore via left click (In Place / Edit modes)

### ISSUE THREAD

**Issue by VergilUa** [LogicalError/realtime-CSG-for-unity#297] opened 2019-08-24 12:09 UTC
For some reason during after version upgrades (multiple, I haven't payed attention to this for a while) I'm unable to select brushes anymore via left clicks.
Only models / gameobjects behind brushes are selected. RealtimeCSG is enabled in scene view.

This is on Unity 2019.2.0f1 and RealtimeCSG v.1557.

Not a big deal, but a little bit of a nuisance. Is there something I'm missing?

**Comment by VergilUa** [comment] 2019-08-25 15:43
This happens in "Place" mode. In surface mode brushes are selected just fine.

**Comment by LogicalError** [comment] 2019-09-11 10:49
Is the problem fixed if you switch between edit modes and back again?

**Comment by VergilUa** [comment] 2019-09-11 11:00
> Is the problem fixed if you switch between edit modes and back again?

Nope, it still selects objects behind brushes in place / edit mode. 
Surface mode selects them correctly.

So its related to both "Place" and "Edit" modes.

**Comment by LogicalError** [comment] 2019-09-11 11:02
The objects you're trying to select, are these brushes or some other kind of objects? if so, what kind of objects?

**Comment by VergilUa** [comment] 2019-09-11 11:08
> The objects you're trying to select, are these brushes or some other kind of objects? if so, what kind of objects?

Brushes. Behind those brushes are default objects. (Meshes, terrain etc)
![GIF](https://user-images.githubusercontent.com/24496266/64692349-8fdba000-d49d-11e9-9254-38fd26dd3c69.gif)

**Comment by LogicalError** [comment] 2019-09-11 11:10
So this happens on renderers behind the brushes? I'll take a look

**Comment by Kerfuffles** [comment] 2022-04-14 09:13
Did this get fixed?

**Comment by Kerfuffles** [comment] 2022-06-10 00:57
I am unable to reproduce this issue. OP has not responded in several months, so I am going to go ahead and close it.

**Closed by Kerfuffles** 2022-06-10 00:57 UTC
Labels: Bug
