### ISSUE TITLE
[FIX AVAILABLE] subtractive operation not working.

### ISSUE THREAD

**Issue by kdgalla** [LogicalError/realtime-CSG-for-unity#12] opened 2016-09-18 21:57 UTC
I have a brush that is a large box, I'm trying to subtract and operation that I had built to make the box into a Gothic vaulted ceiling. Nothing actually happens though, except I get a warning message that says "found transform, but should be impossible". If I remove the operation from the model and then put it back, it will work for a short time, but if I try to make further changes or play the scene, then it breaks again. I have a repro project. Please let me know where I can send it to privately,

**Comment by LogicalError** [comment] 2016-09-19 08:06
Hi, what version are you using? Could you send me your scene so I can look at it?
Thanks

**Comment by kdgalla** [comment] 2016-09-19 11:02
Thanks. I sent the project in a *.rar file. I'm using version 1.207 (downloaded on Saturday from asset store) on Unity 5.4.1f1(64bit).

**Comment by LogicalError** [comment] 2016-09-19 13:17
I looked at this and this is indeed a bug..
In your prefab, the operations that are marked as pass-through somehow don't behave as if they're pass-through .. 
In the meantime, in this particular case you can set those operations to "additive" and this should make it work. It might need a rebuild before it's detected, and that's a second issue in this scene ..
I'll take a look at it.. 
Thanks for the bug report!

**Comment by LogicalError** [comment] 2016-09-19 14:17
It seems the "subtract_gothic_vault" operation is just .. ignored somehow .. everything below it works properly. A simpler temporary workaround would be to set all minus_gothic_arch to subtractive and set minus_gothic_vault and subtract_gothic_vault to pass-through.

**Comment by LogicalError** [comment] 2016-09-19 18:40
Hi, this problem is now fixed in version 1.211, which you can find on the beta site! 
I'll close this bug report once the bug fix is on the asset store

**Comment by kdgalla** [comment] 2016-09-20 04:28
Cool. Thanks.

**Comment by kdgalla** [comment] 2016-09-27 22:13
Hello, thanks for fixing this! I've noticed something else: In that same repro project, Unity consistently crashes when I delete the prefab called "model" from the scene view and replace it by dragging the prefab from the assets tab to the inspector. I submitted a crash report as it may be a Unity problem as well, but I thought you might be interested in looking at this also.

**Comment by LogicalError** [comment] 2016-09-28 11:38
If you submitted a crash report .. could you give me the bug number? .. I work for Unity so I can use that crash report to see if the problem is in realtime CSG, thanks

**Comment by kdgalla** [comment] 2016-09-29 02:20
It is case 832963.

**Comment by LogicalError** [comment] 2016-09-29 17:37
ok, this crash seems to be caused by realtime CSG. 
I created new ticket for this & I'm closing this "subtractive operation" one since that one is fixed.

**Closed by LogicalError** 2016-09-29 17:37 UTC
Labels: bug
